// <auto-generated />
using System;
using HealthifyApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthifyApp.Data.Migrations
{
    [DbContext(typeof(HealthifyDbContext))]
    [Migration("20241210160514_FixWaterTable")]
    partial class FixWaterTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthifyApp.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fee060ea-585b-4f6d-936c-c2a16864d550"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af59cb6d-c4a5-4ab9-a981-3d8b31080e0d",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEPA44XnlXoowIMCk12UhQPu9MeqkA/psAYbnPWqMfM/fhTAwKWIfok5TbM3L3fKwTw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f5c92ca-1710-420f-979e-4e9bde03287d",
                            TwoFactorEnabled = false,
                            UserName = "User1"
                        },
                        new
                        {
                            Id = new Guid("6f4a58f0-3dfe-405f-a1b5-fc7970b4d6ac"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "959d6643-c4d4-4b6e-b38c-a949623d23c8",
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEAyyaHSQ/p4uQH3ZCPHqIiMAGoohkXt5FkYCv7DIsJkSwy2d5K+h8FsOzX201n3mrA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e033aa7d-6c71-462a-b14d-195279dfbb94",
                            TwoFactorEnabled = false,
                            UserName = "User2"
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.ApplicationUserProfile", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId", "UserProfileId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ApplicationUserProfiles");

                    b.HasData(
                        new
                        {
                            ApplicationUserId = new Guid("fee060ea-585b-4f6d-936c-c2a16864d550"),
                            UserProfileId = new Guid("fe6c9d13-b776-490a-af4d-89de75866877")
                        },
                        new
                        {
                            ApplicationUserId = new Guid("6f4a58f0-3dfe-405f-a1b5-fc7970b4d6ac"),
                            UserProfileId = new Guid("8b718d81-de0f-4836-977d-2bb1fb760765")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.BMICalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the BMI calculation.");

                    b.Property<decimal>("BMI")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The BMI of the user.");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasComment("The category of the BMI.");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the BMI calculation.");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The height of the user.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The weight of the user.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("BMICalculations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75ff4ade-9eca-4ab9-9b38-ebdb08c238e5"),
                            BMI = 24.7m,
                            Category = 2,
                            Date = new DateTime(2024, 12, 10, 18, 5, 11, 611, DateTimeKind.Local).AddTicks(1190),
                            Height = 180m,
                            UserProfileId = new Guid("fe6c9d13-b776-490a-af4d-89de75866877"),
                            Weight = 80m
                        },
                        new
                        {
                            Id = new Guid("252c08d3-661d-4b54-b80a-f66f46fa45df"),
                            BMI = 22m,
                            Category = 2,
                            Date = new DateTime(2024, 12, 10, 18, 5, 11, 611, DateTimeKind.Local).AddTicks(2265),
                            Height = 165m,
                            UserProfileId = new Guid("8b718d81-de0f-4836-977d-2bb1fb760765"),
                            Weight = 60.6m
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the exercise.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasComment("Description of the exercise.");

                    b.Property<int?>("Duration")
                        .HasMaxLength(240)
                        .HasColumnType("int")
                        .HasComment("Duration of the exercise in minutes.");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("URL of the image of the exercise.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the exercise.");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de3eca93-36b4-4ac4-a9cf-28d42c3b76bd"),
                            Description = "A bodyweight exercise for upper body strength.",
                            Duration = 30,
                            ImageUrl = "https://anabolicaliens.com/cdn/shop/articles/199990_400x.png?v=1645089103",
                            Name = "Push-Up"
                        },
                        new
                        {
                            Id = new Guid("b4092117-d761-4c9c-8cee-210e8ae30ab2"),
                            Description = "A lower body exercise for strength and endurance.",
                            Duration = 40,
                            ImageUrl = "https://weighttraining.guide/wp-content/uploads/2016/10/barbell-squat-resized-FIXED-2.png",
                            Name = "Squat"
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the goal.");

                    b.Property<int>("Activity")
                        .HasColumnType("int")
                        .HasComment("The activity of the user.");

                    b.Property<float?>("GoalChest")
                        .HasColumnType("real");

                    b.Property<float?>("GoalHips")
                        .HasColumnType("real");

                    b.Property<int>("GoalType")
                        .HasColumnType("int")
                        .HasComment("The goal chois");

                    b.Property<float?>("GoalWaist")
                        .HasColumnType("real");

                    b.Property<decimal>("GoalWeight")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The user's goal weight.");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the goal start.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d93028d2-790c-46f7-9e56-5ed7a17cf8c7"),
                            Activity = 3,
                            GoalChest = 95f,
                            GoalType = 1,
                            GoalWaist = 85f,
                            GoalWeight = 75m,
                            StartDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            UserProfileId = new Guid("fe6c9d13-b776-490a-af4d-89de75866877")
                        },
                        new
                        {
                            Id = new Guid("8a899892-7f81-4fdb-b7b7-51c9cc4f2a14"),
                            Activity = 4,
                            GoalHips = 97f,
                            GoalType = 2,
                            GoalWeight = 67m,
                            StartDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            UserProfileId = new Guid("8b718d81-de0f-4836-977d-2bb1fb760765")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.NutritionIntake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the nutrition intake.");

                    b.Property<int>("Calories")
                        .HasColumnType("int")
                        .HasComment("The calories intake by user.");

                    b.Property<int>("Carbohydrates")
                        .HasColumnType("int")
                        .HasComment("The carbohydrates intake by user.");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the intake.");

                    b.Property<int>("Fats")
                        .HasColumnType("int")
                        .HasComment("The fats intake by user.");

                    b.Property<int>("Protein")
                        .HasColumnType("int")
                        .HasComment("The protein intake by user.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("NutritionIntake");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d51146c2-0377-4eb3-a274-83e750c16a90"),
                            Calories = 1800,
                            Carbohydrates = 90,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Fats = 45,
                            Protein = 140,
                            UserProfileId = new Guid("fe6c9d13-b776-490a-af4d-89de75866877")
                        },
                        new
                        {
                            Id = new Guid("84a69615-231f-4898-b5b5-51c260b55926"),
                            Calories = 2600,
                            Carbohydrates = 220,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Fats = 63,
                            Protein = 210,
                            UserProfileId = new Guid("8b718d81-de0f-4836-977d-2bb1fb760765")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.ProgressLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the progress log.");

                    b.Property<decimal?>("Chest")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The chest of the user.");

                    b.Property<decimal>("CurrentWeight")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The user's weight as of today.");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the progress log.");

                    b.Property<decimal?>("Hips")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The hips of the user.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.Property<decimal?>("Waist")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The waist of the user.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ProgressLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("36cfd717-eb95-4bc2-96b0-6c43115bd093"),
                            Chest = 100m,
                            CurrentWeight = 79.5m,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            UserProfileId = new Guid("fe6c9d13-b776-490a-af4d-89de75866877"),
                            Waist = 90m
                        },
                        new
                        {
                            Id = new Guid("8ef92cc7-73c2-42f5-b20f-8f5ae99d736e"),
                            CurrentWeight = 60.5m,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Hips = 95m,
                            UserProfileId = new Guid("8b718d81-de0f-4836-977d-2bb1fb760765")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.TargetNutrition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the target nutritional.");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The goal ID.");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The goal name.");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the target nutritional start.");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("int")
                        .HasComment("The calories should intake user.");

                    b.Property<int>("TargetCarbohydrates")
                        .HasColumnType("int")
                        .HasComment("The carbohydrates should intake user.");

                    b.Property<int>("TargetFats")
                        .HasColumnType("int")
                        .HasComment("The fats should intake user.");

                    b.Property<int>("TargetProtein")
                        .HasColumnType("int")
                        .HasComment("The protein should intake user.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("TargetNutritional");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e644660-8046-4b62-9706-fe556cd6888c"),
                            GoalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            GoalName = "Lose weight",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TargetCalories = 2000,
                            TargetCarbohydrates = 100,
                            TargetFats = 50,
                            TargetProtein = 150,
                            UserProfileId = new Guid("fe6c9d13-b776-490a-af4d-89de75866877")
                        },
                        new
                        {
                            Id = new Guid("00e2a268-5604-4172-ac0d-0d2409124676"),
                            GoalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            GoalName = "Gain muscle",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TargetCalories = 2500,
                            TargetCarbohydrates = 200,
                            TargetFats = 60,
                            TargetProtein = 200,
                            UserProfileId = new Guid("8b718d81-de0f-4836-977d-2bb1fb760765")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the user profile.");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("The age of the user.");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The creation of the user account.");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(57)
                        .HasColumnType("nvarchar(57)")
                        .HasComment("The first name of the user.");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasComment("The gender of the user");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The height of the user.");

                    b.Property<bool>("IsActiveProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("indicates whether the profile is active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(57)
                        .HasColumnType("nvarchar(57)")
                        .HasComment("The last name of the user.");

                    b.Property<decimal>("StartingWeight")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The starting weight of the user.");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe6c9d13-b776-490a-af4d-89de75866877"),
                            Age = 30,
                            CreatedOn = new DateTime(2024, 12, 10, 18, 5, 11, 608, DateTimeKind.Local).AddTicks(5588),
                            FirstName = "John",
                            Gender = 1,
                            Height = 180m,
                            IsActiveProfile = true,
                            LastName = "Doe",
                            StartingWeight = 80m
                        },
                        new
                        {
                            Id = new Guid("8b718d81-de0f-4836-977d-2bb1fb760765"),
                            Age = 25,
                            CreatedOn = new DateTime(2024, 12, 10, 18, 5, 11, 610, DateTimeKind.Local).AddTicks(3333),
                            FirstName = "Jane",
                            Gender = 2,
                            Height = 165m,
                            IsActiveProfile = true,
                            LastName = "Smith",
                            StartingWeight = 60m
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.WaterIntake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the water intake.");

                    b.Property<float>("DailyGoal")
                        .HasColumnType("real")
                        .HasComment("The daily goal of the water intake.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("WaterIntakes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57327f74-48ae-412d-8f98-90c0c7830a1d"),
                            DailyGoal = 2.5f,
                            UserProfileId = new Guid("fe6c9d13-b776-490a-af4d-89de75866877")
                        },
                        new
                        {
                            Id = new Guid("49f20023-71f0-4c4d-9b82-51b6f8e9db4d"),
                            DailyGoal = 3f,
                            UserProfileId = new Guid("8b718d81-de0f-4836-977d-2bb1fb760765")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the workout.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Description of the workout.");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasComment("Duration of the workout in minutes.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the workout.");

                    b.Property<DateTime>("ScheduleDateTime")
                        .HasColumnType("datetime2")
                        .HasComment("The schedule date and time of the workout.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6a272b8-884e-4dfd-bd9b-e90b3627ce5d"),
                            Description = "A full-body workout to start the day.",
                            Duration = 60,
                            Name = "Morning Strength",
                            ScheduleDateTime = new DateTime(2024, 12, 10, 19, 5, 11, 612, DateTimeKind.Local).AddTicks(6526),
                            UserProfileId = new Guid("8b718d81-de0f-4836-977d-2bb1fb760765")
                        },
                        new
                        {
                            Id = new Guid("a201966b-ba34-4787-84cf-12d339df5ee6"),
                            Description = "High-intensity cardio for fat burn.",
                            Duration = 45,
                            Name = "Evening Cardio",
                            ScheduleDateTime = new DateTime(2024, 12, 10, 21, 5, 11, 612, DateTimeKind.Local).AddTicks(6064),
                            UserProfileId = new Guid("fe6c9d13-b776-490a-af4d-89de75866877")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.WorkoutExercise", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.HasKey("WorkoutId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("WorkoutExercises");

                    b.HasData(
                        new
                        {
                            WorkoutId = new Guid("b6a272b8-884e-4dfd-bd9b-e90b3627ce5d"),
                            ExerciseId = new Guid("de3eca93-36b4-4ac4-a9cf-28d42c3b76bd"),
                            Reps = 10,
                            Sets = 3
                        },
                        new
                        {
                            WorkoutId = new Guid("a201966b-ba34-4787-84cf-12d339df5ee6"),
                            ExerciseId = new Guid("b4092117-d761-4c9c-8cee-210e8ae30ab2"),
                            Reps = 15,
                            Sets = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.ApplicationUserProfile", b =>
                {
                    b.HasOne("HealthifyApp.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserProfiles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("ApplicationUserProfiles")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.BMICalculation", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("BMICalculations")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Goal", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("Goals")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.NutritionIntake", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("NutritionIntake")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.ProgressLog", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.TargetNutrition", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("TargetNutritional")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.WaterIntake", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("WaterIntakes")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Workout", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("Workouts")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.WorkoutExercise", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthifyApp.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HealthifyApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HealthifyApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthifyApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HealthifyApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthifyApp.Data.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUserProfiles");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.UserProfile", b =>
                {
                    b.Navigation("ApplicationUserProfiles");

                    b.Navigation("BMICalculations");

                    b.Navigation("Goals");

                    b.Navigation("NutritionIntake");

                    b.Navigation("ProgressLogs");

                    b.Navigation("TargetNutritional");

                    b.Navigation("WaterIntakes");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
