// <auto-generated />
using System;
using HealthifyApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthifyApp.Data.Migrations
{
    [DbContext(typeof(HealthifyDbContext))]
    [Migration("20241203214343_SeedGoalIdAndAppUserProfile")]
    partial class SeedGoalIdAndAppUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthifyApp.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f2617b1-561e-4334-a60b-93180029696a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "930642d0-6cf9-4c98-88a4-6e4c4459d94e",
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ+88wZsRLoh6PnApJ5SStbQsIRs9lUyKBz1Vt8VYdYAjlts7M39RvRaiBH/s8485A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "68711986-3004-436f-8694-4c2f2c0ec89a",
                            TwoFactorEnabled = false,
                            UserName = "User1"
                        },
                        new
                        {
                            Id = new Guid("f9cde5dc-32d6-4e50-bee3-53e789d7eab8"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7507be9e-952e-4356-a271-275e87262c17",
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEFutjqv/FgcU/hI17WkKCPAgGMKv9L7u/ibgI7aTBJ81Q8DBJlhXCwSyvcBSN5dbOA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3e774fc7-3ec3-4ded-b60d-0c61cab4ea86",
                            TwoFactorEnabled = false,
                            UserName = "User2"
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.ApplicationUserProfile", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApplicationUserId", "UserProfileId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ApplicationUserProfiles");

                    b.HasData(
                        new
                        {
                            ApplicationUserId = new Guid("0f2617b1-561e-4334-a60b-93180029696a"),
                            UserProfileId = new Guid("1639e91a-60b1-4308-88c7-e6203eba4404")
                        },
                        new
                        {
                            ApplicationUserId = new Guid("f9cde5dc-32d6-4e50-bee3-53e789d7eab8"),
                            UserProfileId = new Guid("a6d9f08f-bd55-4b2c-8561-bfc4178266a3")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.BMICalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the BMI calculation.");

                    b.Property<decimal>("BMI")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The BMI of the user.");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasComment("The category of the BMI.");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the BMI calculation.");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The height of the user.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The weight of the user.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("BMICalculations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e326d45-8270-4cbd-af83-201209ab804a"),
                            BMI = 24.7m,
                            Category = 2,
                            Date = new DateTime(2024, 12, 3, 23, 43, 41, 86, DateTimeKind.Local).AddTicks(1540),
                            Height = 180m,
                            UserProfileId = new Guid("1639e91a-60b1-4308-88c7-e6203eba4404"),
                            Weight = 80m
                        },
                        new
                        {
                            Id = new Guid("9fbdf6af-2727-43c8-ad64-3792233f608e"),
                            BMI = 22m,
                            Category = 2,
                            Date = new DateTime(2024, 12, 3, 23, 43, 41, 86, DateTimeKind.Local).AddTicks(6193),
                            Height = 165m,
                            UserProfileId = new Guid("a6d9f08f-bd55-4b2c-8561-bfc4178266a3"),
                            Weight = 60.6m
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the exercise.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasComment("Description of the exercise.");

                    b.Property<int?>("Duration")
                        .HasMaxLength(240)
                        .HasColumnType("int")
                        .HasComment("Duration of the exercise in minutes.");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("URL of the image of the exercise.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the exercise.");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("098b4b05-056a-4cef-acd0-ef8e4bb823e9"),
                            Description = "A bodyweight exercise for upper body strength.",
                            Duration = 30,
                            ImageUrl = "https://anabolicaliens.com/cdn/shop/articles/199990_400x.png?v=1645089103",
                            Name = "Push-Up"
                        },
                        new
                        {
                            Id = new Guid("fdddfcd6-21c0-421e-a276-519f0368110b"),
                            Description = "A lower body exercise for strength and endurance.",
                            Duration = 40,
                            ImageUrl = "https://weighttraining.guide/wp-content/uploads/2016/10/barbell-squat-resized-FIXED-2.png",
                            Name = "Squat"
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the goal.");

                    b.Property<int>("Activity")
                        .HasColumnType("int")
                        .HasComment("The activity of the user.");

                    b.Property<float?>("GoalChest")
                        .HasColumnType("real");

                    b.Property<float?>("GoalHips")
                        .HasColumnType("real");

                    b.Property<int>("GoalType")
                        .HasColumnType("int")
                        .HasComment("The goal chois");

                    b.Property<float?>("GoalWaist")
                        .HasColumnType("real");

                    b.Property<decimal>("GoalWeight")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The user's goal weight.");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the goal start.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd2256e1-d47e-48f4-a6ee-ea2d1ee39c34"),
                            Activity = 3,
                            GoalChest = 95f,
                            GoalType = 1,
                            GoalWaist = 85f,
                            GoalWeight = 75m,
                            StartDate = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            UserProfileId = new Guid("1639e91a-60b1-4308-88c7-e6203eba4404")
                        },
                        new
                        {
                            Id = new Guid("a9752608-0b7b-4215-acd3-2c98a83cfba0"),
                            Activity = 4,
                            GoalHips = 97f,
                            GoalType = 2,
                            GoalWeight = 67m,
                            StartDate = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            UserProfileId = new Guid("a6d9f08f-bd55-4b2c-8561-bfc4178266a3")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.NutritionIntake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the nutrition intake.");

                    b.Property<int>("Calories")
                        .HasColumnType("int")
                        .HasComment("The calories intake by user.");

                    b.Property<int>("Carbohydrates")
                        .HasColumnType("int")
                        .HasComment("The carbohydrates intake by user.");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the intake.");

                    b.Property<int>("Fats")
                        .HasColumnType("int")
                        .HasComment("The fats intake by user.");

                    b.Property<int>("Protein")
                        .HasColumnType("int")
                        .HasComment("The protein intake by user.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("NutritionIntake");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1dfd129e-1c1c-41ec-bf42-1cbcf656f012"),
                            Calories = 1800,
                            Carbohydrates = 90,
                            Date = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Fats = 45,
                            Protein = 140,
                            UserProfileId = new Guid("1639e91a-60b1-4308-88c7-e6203eba4404")
                        },
                        new
                        {
                            Id = new Guid("60c3c090-ddd7-432c-9c8d-0286d208e658"),
                            Calories = 2600,
                            Carbohydrates = 220,
                            Date = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Fats = 63,
                            Protein = 210,
                            UserProfileId = new Guid("a6d9f08f-bd55-4b2c-8561-bfc4178266a3")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.ProgressLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the progress log.");

                    b.Property<decimal?>("Chest")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The chest of the user.");

                    b.Property<decimal>("CurrentWeight")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The user's weight as of today.");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the progress log.");

                    b.Property<decimal?>("Hips")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The hips of the user.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.Property<decimal?>("Waist")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The waist of the user.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ProgressLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b3a86c4e-970b-4c28-8bd1-872ec3955f96"),
                            Chest = 100m,
                            CurrentWeight = 79.5m,
                            Date = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            UserProfileId = new Guid("1639e91a-60b1-4308-88c7-e6203eba4404"),
                            Waist = 90m
                        },
                        new
                        {
                            Id = new Guid("3f47ce38-8366-4813-bab6-c5fcd2034b6a"),
                            CurrentWeight = 60.5m,
                            Date = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            Hips = 95m,
                            UserProfileId = new Guid("a6d9f08f-bd55-4b2c-8561-bfc4178266a3")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.TargetNutrition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the target nutritional.");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The goal ID.");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("The goal name.");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the target nutritional start.");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("int")
                        .HasComment("The calories should intake user.");

                    b.Property<int>("TargetCarbohydrates")
                        .HasColumnType("int")
                        .HasComment("The carbohydrates should intake user.");

                    b.Property<int>("TargetFats")
                        .HasColumnType("int")
                        .HasComment("The fats should intake user.");

                    b.Property<int>("TargetProtein")
                        .HasColumnType("int")
                        .HasComment("The protein should intake user.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("TargetNutritional");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0979eb07-667c-44ae-bac4-f7d0ae8733b0"),
                            GoalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            GoalName = "Lose weight",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TargetCalories = 2000,
                            TargetCarbohydrates = 100,
                            TargetFats = 50,
                            TargetProtein = 150,
                            UserProfileId = new Guid("1639e91a-60b1-4308-88c7-e6203eba4404")
                        },
                        new
                        {
                            Id = new Guid("642ead46-a237-4070-a6ef-126fd4f04093"),
                            GoalId = new Guid("00000000-0000-0000-0000-000000000000"),
                            GoalName = "Gain muscle",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TargetCalories = 2500,
                            TargetCarbohydrates = 200,
                            TargetFats = 60,
                            TargetProtein = 200,
                            UserProfileId = new Guid("a6d9f08f-bd55-4b2c-8561-bfc4178266a3")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the user profile.");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasComment("The age of the user.");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("The creation of the user account.");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(57)
                        .HasColumnType("nvarchar(57)")
                        .HasComment("The first name of the user.");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasComment("The gender of the user");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The height of the user.");

                    b.Property<bool>("IsActiveProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("indicates whether the profile is active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(57)
                        .HasColumnType("nvarchar(57)")
                        .HasComment("The last name of the user.");

                    b.Property<decimal>("StartingWeight")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("The starting weight of the user.");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1639e91a-60b1-4308-88c7-e6203eba4404"),
                            Age = 30,
                            CreatedOn = new DateTime(2024, 12, 3, 23, 43, 41, 81, DateTimeKind.Local).AddTicks(1703),
                            FirstName = "John",
                            Gender = 1,
                            Height = 180m,
                            IsActiveProfile = false,
                            LastName = "Doe",
                            StartingWeight = 80m
                        },
                        new
                        {
                            Id = new Guid("a6d9f08f-bd55-4b2c-8561-bfc4178266a3"),
                            Age = 25,
                            CreatedOn = new DateTime(2024, 12, 3, 23, 43, 41, 84, DateTimeKind.Local).AddTicks(4790),
                            FirstName = "Jane",
                            Gender = 2,
                            Height = 165m,
                            IsActiveProfile = false,
                            LastName = "Smith",
                            StartingWeight = 60m
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.WaterIntake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the water intake.");

                    b.Property<float?>("Consumed")
                        .HasColumnType("real")
                        .HasComment("The consumed water of the user.");

                    b.Property<float>("DailyGoal")
                        .HasColumnType("real")
                        .HasComment("The daily goal of the water intake.");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("The date of the water intake.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("WaterIntakes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2db471e2-a0e4-4aac-94ed-4e5064201bf7"),
                            Consumed = 2f,
                            DailyGoal = 2.5f,
                            Date = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            UserProfileId = new Guid("1639e91a-60b1-4308-88c7-e6203eba4404")
                        },
                        new
                        {
                            Id = new Guid("0e5876ca-ac1a-434d-9f3b-ec32ed501803"),
                            Consumed = 2.8f,
                            DailyGoal = 3f,
                            Date = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            UserProfileId = new Guid("a6d9f08f-bd55-4b2c-8561-bfc4178266a3")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key for the workout.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Description of the workout.");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasComment("Duration of the workout in minutes.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Name of the workout.");

                    b.Property<DateTime>("ScheduleDateTime")
                        .HasColumnType("datetime2")
                        .HasComment("The schedule date and time of the workout.");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The user profile ID.");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e86d3c82-6e9c-4d43-94f4-f2c00a737a71"),
                            Description = "A full-body workout to start the day.",
                            Duration = 60,
                            Name = "Morning Strength",
                            ScheduleDateTime = new DateTime(2024, 12, 4, 0, 43, 41, 90, DateTimeKind.Local).AddTicks(696),
                            UserProfileId = new Guid("a6d9f08f-bd55-4b2c-8561-bfc4178266a3")
                        },
                        new
                        {
                            Id = new Guid("e78e4913-4dc7-4463-9d92-0bd3eacb7cbd"),
                            Description = "High-intensity cardio for fat burn.",
                            Duration = 45,
                            Name = "Evening Cardio",
                            ScheduleDateTime = new DateTime(2024, 12, 4, 2, 43, 41, 89, DateTimeKind.Local).AddTicks(9708),
                            UserProfileId = new Guid("1639e91a-60b1-4308-88c7-e6203eba4404")
                        });
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.WorkoutExercise", b =>
                {
                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Sets")
                        .HasColumnType("int");

                    b.HasKey("WorkoutId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("WorkoutExercises");

                    b.HasData(
                        new
                        {
                            WorkoutId = new Guid("e86d3c82-6e9c-4d43-94f4-f2c00a737a71"),
                            ExerciseId = new Guid("098b4b05-056a-4cef-acd0-ef8e4bb823e9"),
                            Reps = 10,
                            Sets = 3
                        },
                        new
                        {
                            WorkoutId = new Guid("e78e4913-4dc7-4463-9d92-0bd3eacb7cbd"),
                            ExerciseId = new Guid("fdddfcd6-21c0-421e-a276-519f0368110b"),
                            Reps = 15,
                            Sets = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.ApplicationUserProfile", b =>
                {
                    b.HasOne("HealthifyApp.Data.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserProfiles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("ApplicationUserProfiles")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.BMICalculation", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("BMICalculations")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Goal", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("Goals")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.NutritionIntake", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("NutritionIntake")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.ProgressLog", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("ProgressLogs")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.TargetNutrition", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("TargetNutritional")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.WaterIntake", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("WaterIntakes")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Workout", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.UserProfile", "UserProfile")
                        .WithMany("Workouts")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.WorkoutExercise", b =>
                {
                    b.HasOne("HealthifyApp.Data.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthifyApp.Data.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("HealthifyApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("HealthifyApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthifyApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("HealthifyApp.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthifyApp.Data.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUserProfiles");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.UserProfile", b =>
                {
                    b.Navigation("ApplicationUserProfiles");

                    b.Navigation("BMICalculations");

                    b.Navigation("Goals");

                    b.Navigation("NutritionIntake");

                    b.Navigation("ProgressLogs");

                    b.Navigation("TargetNutritional");

                    b.Navigation("WaterIntakes");

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("HealthifyApp.Data.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
